name: chatgpt
description: A new Flutter project.
publish_to: "none"
version: 1.0.1
environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.17
  local_notifier: ^0.1.5
  window_manager: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
